[bones]
"mixamorig:Hips" = "hips"
"mixamorig:Spine" = "spine_01"
"mixamorig:Spine1" = "spine_02"
"mixamorig:Spine2" = "spine_03"
"mixamorig:Neck" = "neck"
"mixamorig:Head" = "head"
"mixamorig:LeftShoulder" = "clavicle_l"
"mixamorig:LeftArm" = "upperarm_l"
"mixamorig:LeftForeArm" = "lowerarm_l"
"mixamorig:LeftHand" = "hand_l"
"mixamorig:RightShoulder" = "clavicle_r"
"mixamorig:RightArm" = "upperarm_r"
"mixamorig:RightForeArm" = "lowerarm_r"
"mixamorig:RightHand" = "hand_r"
"mixamorig:LeftUpLeg" = "thigh_l"
"mixamorig:LeftLeg" = "calf_l"
"mixamorig:LeftFoot" = "foot_l"
"mixamorig:LeftToeBase" = "toe_l"
"mixamorig:RightUpLeg" = "thigh_r"
"mixamorig:RightLeg" = "calf_r"
"mixamorig:RightFoot" = "foot_r"
"mixamorig:RightToeBase" = "toe_r"
